language: php
php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql
  
before_script:
  - wget http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz -P geoipdb/
  - gunzip -f geoipdb/GeoIP.dat.gz
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS test;" -uroot; fi
  
script:
  - phpunit --configuration travis.phpunit.xml.dist